### ISSUE TITLE
Can I use this to make a scripting language?

### ISSUE THREAD

**Issue by assyrianic** [andrewchambers/c#28]
Hello Andrew, I'm Nergal and I'm interesting in forking over this C compiler suite to create a game scripting language. May I have permission? Also, how stable is this compiler suite?

**Comment by andrewchambers** [comment]
Sure, though I would recommend you use a more proven technology like luajit.  For example, this does not currently even manage memory appropriately for use as a library. And almost certainly has many bugs because the only code it has been tested on is itself and nothing else.

Of course, if you understand all the flaws this code probably has and wish to continue, feel free to use it.

**Comment by assyrianic** [comment]
lua is fine but I really need a more C-like language. I did find Pawn but it has no real types (everything is a 32-bit int) and it doesn't support pointers. I require a scripting language that actually uses pointers, not just references.

**Comment by andrewchambers** [comment]
Have you played with libtcc? it is the library component of the tcc compiler and is very complete and can compile C code into memory with full pointer access.

**Comment by assyrianic** [comment]
no but TCC hasn't been updated since 2013 and its file structure is a bit complex and would take some time considering I would need to prune much of its code and simplify semantics and syntax. The scripting language I have in mind would be nearly exactly like C but more cleaned up, organized, and unnecessary stuff removed. The choices are for the sake of speed, simplicity, and not requiring to learn another language just to script.
