### ISSUE TITLE
There is an bug in the foldbinop function

### ISSUE THREAD

**Issue by chneg3** [andrewchambers/c#33]
Should be:
`		case '+':  
			if(l->p && r->p)  
				return 0;  
			if(l->p)  
			+	return mkconst(l->p, l->v + r->v);  
			if(r->p)  
			+	return mkconst(r->p, l->v + r->v);  
			return mkconst(0, l->v + r->v);  
`

**Comment by andrewchambers** [comment]
Thank you for the bug reports :).

Actually there is a new unreleased C compiler being worked on by one of my friends that is much more advanced and complete - I will definitely link it from this project and update my readme soon, I think you would be interested in that one.

Because of that project, I'm not really working on this one. Feel free to keep reporting issues, but I probably won't be fixing them soon.

**Comment by chneg3** [comment]
Thank you for your reminder.

**Comment by andrewchambers** [comment]
Please try https://github.com/michaelforney/cc instead.
